### ISSUE TITLE
Shall ants strike back?

### ISSUE THREAD

**Issue by ep69** [Cropsey/fsp2#2]
Borci (@dzejar @wozniakjan), napadlo me, ze kdybych mel chvilku, zkusil bych se povrtat v tech mravencich z lonska, ale nechci si to na sebe brat, pokud by to mela byt urcite realna soucast reseni - kdybych to nakonec nestihl. Planujete na tom vysivat vy?
Pripadne je nejaka jina NICE_TO_HAVE cast, na kterou bych pripadne mohl pri chvilce mrknout?

**Comment by dzejar** [comment]
Na mravencích nikdo z nás asi nemá v plánu dělat, tak klidně. Ale ideální cesta asi povede přes simulated annealing...

**Comment by wozniakjan** [comment]
mravenci by podle me stali za hrich, libilo by se mi mit neco jineho nez maji vsichni, i pro porovnani. Ale ja urcite mravence nedam, budu rad kdyz na to tento tyden kouknu aspon dva vecery...
blbe je, ze ten odevzdavaci formular bere jen jediny soubor, takze vsechno prasime do jednoho souboru zatim
